
GET http://localhost:3000/address


# GET http://localhost:3000/address/1

# POST  http://localhost:3000/address
# Content-Type: application/json

# {
#     "street": "Rua das Manguapas",
#     "state": "Pernambuco",
#     "district": "Recife",
#     "complement": "Perto do seu cu",
#     "zipCode": "1231315"
# }

# PUT  http://localhost:3000/address/1
# Content-Type: application/json

# {
#   "street": "Rua dos Manguapes, 190"
# }


# DELETE   http://localhost:3000/address/1


