
GET http://localhost:3000/address


# GET http://localhost:3000/address/1

# POST  http://localhost:3000/address
# Content-Type: application/json

# {
#     "street": "Rua dos Corons",
#     "state": "Cornolândia",
#     "district": "Corninho",
#     "complement": "Perto do Bar dos Cornos",
#     "zipCode": "1312312"
# }

# PUT  http://localhost:3000/address/1
# Content-Type: application/json

# {
#   "street": "Rua dos Manguapes, 190"
# }


# DELETE   http://localhost:3000/address/1


