
# GET http://localhost:3000/client


# GET http://localhost:3000/client/1

# POST  http://localhost:3000/client
# Content-Type: application/json

# {
#   "name": "carlos",
#   "login": "carlos_gay",
#   "password": "1234131",
#   "email": "carlos_gay@email.com",
#   "tel": "81912345678",
#   "birth": "01/01/2005", 
#   "address_id": 1
# }

# PUT  http://localhost:3000/client/1
# Content-Type: application/json

# {
#    "address_id": 1
# }


# DELETE   http://localhost:3000/client/1


