
# GET http://localhost:3000/order

# GET http://localhost:3000/order/1

# POST  http://localhost:3000/order
# Content-Type: application/json

# {
#   "date": "01-01-2000",
#   "totalValue": 1000,
#   "client_id": 3,
#   "address_id":2
# }

# PUT  http://localhost:3000/order/1
# Content-Type: application/json

# {
#    "address_id":2
# }


# DELETE   http://localhost:3000/order/1


