
# GET http://localhost:3000/product

# GET http://localhost:3000/product/1

# POST  http://localhost:3000/product
# Content-Type: application/json

# {
#   "name": "Casaco preto",
#   "description": "Um casco para aquecer nos dias mais frios",
#   "price": 500,
#   "img": "https://cdn-images.farfetch-contents.com/17/62/17/92/17621792_36776691_600.jpg"
# }

# PUT  http://localhost:3000/product/1
# Content-Type: application/json

# {
#   "name": "Casaco negro"
# }


# DELETE   http://localhost:3000/product/1


